@startuml Enemy1Sm

' //////////////////////// STATE ORGANIZATION ///////////////////////
' Note: StateSmith treats state names and events as case insensitive.
' More info: https://github.com/StateSmith/StateSmith/wiki/PlantUML

state "$parent_alias" as PA

state INITIAL
state SLEEPING

state PATROL {
    state PATROL_MARCH
    state PATROL_END_DELAY
    state PATROL_END_HOP
    ' state PATROL_END_TURN
    [*] -> PATROL_MARCH
}

state JUMP_AROUND

state HUNTING

[*] -> INITIAL


' ///////////////////////// STATE HANDLERS /////////////////////////
' Syntax: https://github.com/StateSmith/StateSmith/wiki/Behaviors

PA --> HUNTING: DAMAGED
PA --> JUMP_AROUND: HEARD_SHOT

INITIAL --> PATROL: [obj.playerDist() <= 8]
INITIAL: enter / obj.swellSpeed = 2;

SLEEPING: enter / obj.swellSpeed = 2;
' SLEEPING: enter / timer.set(rand(5, 10));
SLEEPING --> JUMP_AROUND: [obj.playerDist() <= 8]

' PATROL: enter / timer.set(rand(5, 10));
' PATROL -> SLEEPING: [timer.elapsed()]
PATROL_MARCH: enter / obj.swellSpeed = 4;
PATROL_MARCH: enter / obj.stallTracker.reset();
PATROL_MARCH: do / obj.stallTracker.update();
PATROL_MARCH: do / obj.doPatrolMarch();
PATROL_MARCH --> PATROL_END_DELAY: [obj.isPatrolEnd()]

PATROL_END_DELAY: enter / timer.set(0.5);
PATROL_END_DELAY --> PATROL_END_HOP: [timer.elapsed()]

PATROL_END_HOP: enter / obj.smallVerticalHop();
PATROL_END_HOP --> PATROL_MARCH: [obj.groundObject] / obj.patrolTurn();

HUNTING --> SLEEPING: PLAYER_DEAD

JUMP_AROUND: enter / obj.swellSpeed = 8;
JUMP_AROUND: enter / timer.set(rand(4, 6));
JUMP_AROUND: do / obj.jumpAround();
' JUMP_AROUND --> SLEEPING: [obj.playerDist() >= 10]
JUMP_AROUND --> SLEEPING: [timer.elapsed()]
JUMP_AROUND -r-> HUNTING: [obj.playerDist() <= 4]
JUMP_AROUND -r-> HUNTING: HEARD_SHOT

HUNTING: enter / obj.swellSpeed = 30;
HUNTING: enter / timer.set(rand(5,15));
HUNTING: enter / obj.stallTracker.reset();
HUNTING: do / obj.stallTracker.update();
HUNTING: do / obj.doHuntPlayer();
HUNTING: HEARD_SHOT / 
HUNTING -l-> JUMP_AROUND: [timer.elapsed()]

' //////////////////////// StateSmith config ////////////////////////
' The below special comment block sets the StateSmith configuration.
' More info: https://github.com/StateSmith/StateSmith/issues/335

/'! $CONFIG : toml
[SmRunnerSettings]
transpilerId = "JavaScript"

[RenderConfig]
AutoExpandedVars = """
    timer: new Timer(0),
    obj: null, // need to set this to instance of Enemy1 before calling start()
    """
'/
@enduml