@startuml Enemy1Sm

' //////////////////////// STATE ORGANIZATION ///////////////////////
' Note: StateSmith treats state names and events as case insensitive.
' More info: https://github.com/StateSmith/StateSmith/wiki/PlantUML

state SLEEPING

state AWAKE {
    state JUMP_AROUND
    state HUNTING
}

[*] -> SLEEPING


' ///////////////////////// STATE HANDLERS /////////////////////////
' Syntax: https://github.com/StateSmith/StateSmith/wiki/Behaviors

SLEEPING: enter / obj.swellSpeed = 2;
SLEEPING --> JUMP_AROUND: [obj.playerDist() <= 8]

AWAKE -up-> SLEEPING: PLAYER_DEAD

JUMP_AROUND: enter / obj.swellSpeed = 8;
JUMP_AROUND: do / obj.jumpAround();
JUMP_AROUND --> SLEEPING: [obj.playerDist() >= 10]
JUMP_AROUND --> HUNTING: DAMAGED
JUMP_AROUND --> HUNTING: [obj.playerDist() <= 4]

HUNTING: enter / obj.swellSpeed = 30;
HUNTING: enter/ obj.huntingTimer.set(10);
HUNTING: do / obj.jumpTowardsPlayer();
HUNTING --> JUMP_AROUND: [obj.huntingTimer.elapsed()]


' //////////////////////// StateSmith config ////////////////////////
' The below special comment block sets the StateSmith configuration.
' More info: https://github.com/StateSmith/StateSmith/issues/335

/'! $CONFIG : toml
[SmRunnerSettings]
transpilerId = "JavaScript"

[RenderConfig]
AutoExpandedVars = """
    obj: null, // need to set this to instance of Enemy1 before calling start()
    """
'/
@enduml