@startuml Enemy1Sm

' //////////////////////// STATE ORGANIZATION ///////////////////////
' Note: StateSmith treats state names and events as case insensitive.
' More info: https://github.com/StateSmith/StateSmith/wiki/PlantUML

state PASSIVE {
    state SLEEPING

    state PATROL {
        state PATROL_MARCH
        ' state PATROL_HOP
        [*] -> PATROL_MARCH
    }

    state JUMP_AROUND
}

state HUNTING

[*] --> PATROL
' [*] -> SLEEPING


' ///////////////////////// STATE HANDLERS /////////////////////////
' Syntax: https://github.com/StateSmith/StateSmith/wiki/Behaviors

PASSIVE --> HUNTING: DAMAGED

SLEEPING: enter / obj.swellSpeed = 2;
SLEEPING: enter / obj.timer.set(rand(5, 10));
SLEEPING -> PATROL: [obj.timer.elapsed()]
SLEEPING --> JUMP_AROUND: [obj.playerDist() <= 5]

PATROL: enter / obj.timer.set(rand(5, 10));
PATROL -> SLEEPING: [obj.timer.elapsed()]
PATROL_MARCH: enter / obj.swellSpeed = 4;
PATROL_MARCH: do / obj.doPatrolMarch();

HUNTING --> SLEEPING: PLAYER_DEAD

JUMP_AROUND: enter / obj.swellSpeed = 8;
JUMP_AROUND: do / obj.jumpAround();
JUMP_AROUND --> SLEEPING: [obj.playerDist() >= 10]
JUMP_AROUND -r-> HUNTING: [obj.playerDist() <= 4]

HUNTING: enter / obj.swellSpeed = 30;
HUNTING: enter/ obj.timer.set(10);
HUNTING: do / obj.doHuntPlayer();
HUNTING -l-> JUMP_AROUND: [obj.timer.elapsed()]


' //////////////////////// StateSmith config ////////////////////////
' The below special comment block sets the StateSmith configuration.
' More info: https://github.com/StateSmith/StateSmith/issues/335

/'! $CONFIG : toml
[SmRunnerSettings]
transpilerId = "JavaScript"

[RenderConfig]
AutoExpandedVars = """
    obj: null, // need to set this to instance of Enemy1 before calling start()
    """
'/
@enduml